version: "3.9"

services:
  omoponfhir:
    image: smartchartsuite/omoponfhir-main-v54-r4:0.1.1
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://omop54:5432/omop54
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - SERVERBASE_URL=http://localhost:8080/fhir
      - SMART_INTROSPECTURL=http://localhost:8080/smart/introspect
      - SMART_AUTHSERVERURL=http://localhost:8080/smart/authorize
      - SMART_TOKENSERVERURL=http://localhost:8080/smart/token
      - AUTH_BEARER=12345
      - AUTH_BASIC=client:secret
      - FHIR_READONLY=False
      - MEDICATION_TYPE=code
    depends_on:
      omop54:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  omop54:
    image: smartchartsuite/omop-cdm-54-postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - CONSTRAINTS=false
      - OMOP_ON_FHIR=true
    volumes:
      - ./vocab:/VOCAB
    healthcheck:
      test: ["CMD", "./omoponfhir/healthcheck.sh"]
      interval: 15s
      timeout: 10s
      retries: 10000
